export const markup = `
        <div class="tour-cover garden-only" id="tour-cover" aria-hidden="true"></div>
        <div class="letterbox garden-only" id="letterbox" hidden><i></i><i></i><strong id="cine-title"></strong><small>Enter or click to skip</small></div>
        <div class="speech-layer garden-only" id="speech" aria-hidden="true"></div>
        <div class="tour-caption garden-only" id="tour-caption" aria-live="polite"><button class="tour-info" id="tour-info" title="Full game guide">ⓘ Full guide</button><small id="tour-step"></small><strong id="tour-title"></strong><span id="tour-text"></span><div class="tour-dots" id="tour-dots" aria-hidden="true"></div></div>
        <div class="bumble-alert garden-only" id="bumble-alert" hidden><div class="alert-banner" role="alert"><strong>⚠ ALERT</strong><span id="alert-text">BUMBLEBEE INCOMING</span><em id="alert-count">4</em></div></div>
        <div class="heist-banner garden-only" id="heist-banner" hidden role="status"><strong id="heist-title">🍯 HONEY THIEF!</strong><span id="heist-text"></span><span class="heist-hits" id="heist-hits" aria-hidden="true"></span></div>
        <nav class="fs-bar garden-only" id="fs-bar" aria-label="Fullscreen shortcuts"><span class="fs-keys"><span><kbd>WASD</kbd> move</span><span><kbd>SPACE</kbd> up</span><span><kbd>C</kbd> down</span><span><kbd>SHIFT</kbd> boost</span></span><span class="fs-actions"><button data-fs="controls-toggle">🎮 Controls <kbd>H</kbd></button><button data-fs="view">👁 View <kbd>V</kbd></button><button data-fs="sound">♪ Sound</button><button data-fs="pause">Ⅱ Pause <kbd>P</kbd></button><button data-fs="fullscreen">✕ Exit fullscreen <kbd>F</kbd></button></span></nav>
        <div class="bumble-marker garden-only" id="bumble-marker" hidden aria-hidden="true"><i></i><span>🐝</span></div>
        <div class="reticle garden-only" id="reticle" hidden aria-hidden="true"></div>
        <aside class="controls-panel garden-only" id="controls-panel" aria-label="Controls"><header id="controls-grip" title="Drag to move"><span>⠿ CONTROLS</span><button id="controls-close" title="Hide controls (H)" aria-label="Hide controls">×</button></header><div id="controls-list"></div><details class="mixer" id="mixer"><summary>🎚 Sound mixer</summary><div id="mixer-list"></div><button id="mixer-reset" title="Set every slider back to 100 %">↺ Reset to default</button></details><details class="mixer" id="game-settings"><summary>⚙ Game settings</summary><label class="mix-row"><span>Rain cloud after bumps</span><input type="range" id="rain-bumps" min="3" max="10" step="1" value="5" aria-label="Bumps before the rain cloud"><output>5</output></label><label class="mix-row"><span>…within seconds</span><input type="range" id="rain-window" min="10" max="40" step="5" value="20" aria-label="Time window for the bumps"><output>20 s</output></label><label class="mix-row boss-row"><span>Final boss: the wasp</span><input type="checkbox" id="boss-mode" checked aria-describedby="boss-mode-note"><output id="boss-mode-note">4:00 · 450</output></label></details></aside>
        <div class="arena-top garden-only">
          <div class="world-title"><span class="live-dot"></span> HONEY RETRIEVAL<small>ROUND <span id="round">01</span></small></div>
          <div class="mission-status" id="mission-status"><div><span>HIVE</span><strong id="honey">0</strong><span id="goal-total">/ 450</span><span id="your-share" class="your-share"></span><span id="percent">0%</span></div><div class="progress-track"><i id="honey-progress"></i><b id="player-progress"></b></div></div>
          <div class="round-clock"><span id="phase">READY</span><strong id="timer">4:00</strong></div>
          <div class="arena-actions"><button id="guide" title="Full game guide" aria-label="Open the full game guide">?</button><button id="controls-toggle" title="Show or hide controls (H)" aria-label="Hide controls" aria-pressed="true">🎮</button><button id="view" title="Switch to bee view (V)" aria-label="Switch to bee view" aria-pressed="false">👁 <span>Bee view</span></button><button id="sound" title="Toggle sound" aria-label="Disable sound" aria-pressed="true">♪ <span>Sound on</span></button><button id="fullscreen" title="Fullscreen (F)" aria-label="Toggle fullscreen">⛶</button><button id="pause" title="Pause game" aria-label="Pause game" disabled>Ⅱ</button></div>
        </div>
        <div class="power-tip garden-only" id="power-tip" hidden role="status"><strong>⚡ NECTAR POWER!</strong><span>Press <kbd>SHIFT</kbd> for a power boost: smash through trees and flowers, send bees flying, and shove the bumblebee away (2 nectar per shove).</span></div>
        <div class="load-tip garden-only" id="load-tip" hidden role="status"><strong>🍯 HEAVY LOAD!</strong><span>Each drop slows you a little. Deliver for bonus points (6+ drops ×1.5, full bag ×2), or keep going: at 6 drops you glow with <b>nectar power</b>, and a power boost (<kbd>SHIFT</kbd>) can <b>shove the bumblebee away</b>.</span></div>
        <div class="rain-overlay garden-only" id="rain-overlay" hidden aria-hidden="true"></div>
        <div class="boss-bar garden-only" id="boss-bar" hidden role="status"><strong>⚠ WASP</strong><span class="boss-hits" id="boss-hits" aria-label="Butt slams landed"></span><small id="boss-swarm"></small></div>
        <div class="swarm-prompt garden-only" id="swarm-prompt" hidden role="status"><div class="swarm-keys"><kbd>X</kbd><kbd>X</kbd><kbd>X</kbd></div><span id="swarm-text">Tap fast: gather the swarm!</span><i class="swarm-taps" id="swarm-taps"></i></div>
        <button class="swarm-attack garden-only" id="swarm-attack" hidden>⚔ ATTACK!<small>click or Enter</small></button>
        <button class="defender-call garden-only" id="defender-call" hidden>🛡 Call 5 defender bees<small>press B · tokens: <b id="defender-count">1</b></small></button>
        <div class="slam-prompt garden-only" id="slam-prompt" hidden role="status"><kbd>SPACE</kbd><strong>BUTT SLAM!</strong></div>
        <div class="victory garden-only" id="victory" hidden aria-live="assertive"><strong>HIVE DEFENDED!</strong><small id="victory-text">The wasp is gone.</small></div>
        <div class="wasted garden-only" id="wasted" hidden aria-live="assertive"><strong>WASTED</strong><small>The wasp smashed the hive and ate the honey.</small></div>
        <div class="demo-badge garden-only" id="demo-badge" hidden role="status"><strong>DEMO</strong><span id="demo-time">0:00</span><span id="demo-label"></span><button id="demo-exit" title="End the demo (Esc)">✕ End <kbd>Esc</kbd></button></div>
        <div class="scene-label garden-only" id="hive-label">HIVE<span>nectar drop-off</span></div>
        <div class="intro garden-only" id="intro"><div><h1>Collect. Return. Repeat.</h1><p id="intro-text">450 nectar. 4 minutes. You + 6 AI scouts. Fly high and low, dodge the clumsy bumblebee, and <b>beware the wasp!</b></p><small id="intro-best" hidden></small><small id="sound-hint">🔊 Click once for sound, then click again or press Enter to fly.</small><button id="demo" class="demo-button" title="Watch a demo of about a minute and a half: the bee flies by itself through everything a round can bring">▶ Watch the demo <span>· 1½ min</span></button></div><button id="start" class="primary play-button" aria-label="Start flight" title="Start flight">▶</button></div>
        <div class="flight-hud garden-only" id="flight-hud" hidden><div class="score" title="Points for delivered nectar; 6+ drops ×1.5, a full bag ×2"><span>SCORE</span><strong id="points">0</strong><small id="best">BEST 0</small></div><div><span id="bag-label">YOUR NECTAR</span><div id="bag" class="bag"></div></div><div class="boost"><span id="boost-label">BOOST READY</span><div><i id="boost-meter"></i></div></div><div class="bee-tokens" id="bee-tokens" hidden title="Bee tokens: press B to call 5 bees out of the hive"><span>🐝</span><strong id="bee-token-count">×1</strong><kbd>B</kbd></div><div class="boost turbo" title="Speed mode: double-tap the direction you fly, or press E (5 s, then 20 s to recharge)"><span id="turbo-label">SPEED READY</span><div><i id="turbo-meter"></i></div></div><div class="power" id="power" title="Collect nectar to charge a power boost"><span id="power-label">NECTAR POWER</span><div class="power-pips" id="power-pips"></div><small id="shoves" hidden title="Power-boost into the bumblebee to shove it away; each shove costs 2 nectar"></small></div><div class="altitude" title="Altitude: Space to climb, C to sink"><span>ALT</span><div class="alt-track"><i id="alt-marker"></i></div><strong id="alt">2.0</strong><div class="alt-keys" aria-hidden="true"><kbd data-k="Space">▲ SPACE</kbd><kbd data-k="KeyC">▼ C</kbd></div></div><button id="home" title="Point to hive">⌂ <span>Return to hive</span></button></div>
        <div class="mobile-controls garden-only" id="touch-controls"><div class="dpad"><button data-key="KeyW" aria-label="Fly forward">↑</button><button data-key="KeyA" aria-label="Fly left">←</button><button data-key="KeyS" aria-label="Fly backward">↓</button><button data-key="KeyD" aria-label="Fly right">→</button></div><div><button data-key="Space" aria-label="Fly up">▲</button><button data-key="KeyC" aria-label="Fly down">▼</button><button data-key="ShiftLeft">Boost</button><button data-key="KeyE" aria-label="Speed mode">Speed</button><button id="touch-swarm" aria-label="Swarm command (tap three times)">🐝 X</button><button id="touch-bees" aria-label="Call 5 bees with a bee token">🐝 B</button></div></div>
        `;
