// The full game guide, shown in the shared dialog from the tour caption or the HUD.
const key = text => `<kbd>${text}</kbd>`;
export const GUIDE_HTML = `<p class="eyebrow">HONEY RETRIEVAL · FULL GUIDE</p><h2>How to play</h2>
<div class="guide">
<h3>Goal</h3><p>Fill the hive with <strong>350 nectar in 3 minutes</strong>, together with 6 AI scouts. Collect glowing honey drops from flowers and deliver them to the golden hive in the centre (fly into its glowing ring).</p>
<h3>Flying</h3><p>${key('W')}${key('A')}${key('S')}${key('D')} or arrows: fly · ${key('SPACE')} climb · ${key('C')} sink · ${key('SHIFT')} boost (2.5 s, recharges faster with every drop) · ${key('E')} or double-tap the key you fly with: <strong>speed mode</strong> (5 s, then 20 s to recharge; see the blue SPEED meter) · drag to rotate, scroll to zoom.</p>
<p>${key('V')} <strong>Bee view</strong>: first person. Click to steer with the mouse (or drag); ${key('W')} flies where you look, ${key('A')}/${key('D')} strafe, ${key('←')}/${key('→')} turn.</p>
<h3>Load and points</h3><p>Your bag holds 8 drops; they show as pollen baskets on your legs. From 4 drops on you slow down a little, more with every drop. Each delivered drop scores <strong>10 points</strong>, ×1.5 for 6–7 drops and ×2 for a full bag. The honeycomb ring around the hive shows the honey: your cells are <strong>orange</strong>. Your best round this session is kept.</p>
<h3>Goal and highscore</h3><p>Reach the goal and the hive overflows: honey floods the garden, the trees turn gold and all bees form a honeycomb. After every round your score goes on the session highscore table; type your initials (three letters or digits).</p>
<h3>Nectar power</h3><p>Every 6 drops charge your bee: it glows. Golden rings pulse up around your bee whenever a boost starts. The next boost is a <strong>power boost</strong>: it knocks trees and flowers over (they stand up again), sends bees flying, and can <strong>shove the bumblebee away</strong> for 2 drops per shove.</p>
<h3>The bumblebee</h3><p>Around mid-round a red alert announces a clumsy bumblebee. It crashes through the garden and knocks bees around (they spill nectar and see stars). Dodge it with altitude and boost. Later it comes back, bumbles around, then <strong>sits on the hive and drinks honey</strong>: fly into it <strong>3 times</strong> to knock it off (a power bump counts double).</p>
<h3>Bumps and bubbles</h3><p>Bees, trees, flowers and the hive are solid. Bumping into things makes comic sound words, and the scouts complain in speech bubbles.</p>
<h3>Rain cloud</h3><p>Bump <strong>5 times within 20 seconds</strong> and a little rain cloud gathers above your bee: wet wings fly slower for 5 seconds. Then the cloud drifts off and your bee shakes itself dry. Change both numbers under ⚙ <strong>Game settings</strong> in the controls panel.</p>
<h3>Screen and sound</h3><p>${key('H')} or 🎮 shows the controls panel (drag it anywhere) · ${key('F')} fullscreen · ${key('P')} pause · ♪ sound on/off. The 🎚 sound mixer in the panel sets master, bees, your bee, bumblebee, voices, effects, ambience and background (Summer meadow, Synthwave, Off).</p>
</div>`;
